### ISSUE TITLE
Landmarks Matlab Code

### ISSUE THREAD

**Issue by mayaalhinai** [Tejesh-Raut/Face-Recognition-using-MATLAB#1]
I need mtalab code for landmarks detection using canny detector. The Landmarks are shown in the following image:
![f1](https://user-images.githubusercontent.com/49141153/55702838-e32a5d80-59e8-11e9-8a58-de38f1fe46b4.png)
[](url)

**Comment by bjornrd** [comment]
A bit more information would certainly help -- What do you need to know about the landmarks?
